### ISSUE TITLE
Build App Structure

### ISSUE THREAD

**Issue by AldonIsenberg11** [AldonIsenberg11/Wrestling#16]
We need to start off with getting the website structure setup

We are using Vue.JS:

- **.vue file Specs**: https://vue-loader.vuejs.org/en/start/spec.html
- **Vue Structure**: https://vuex.vuejs.org/en/structure.html
- **Vue Language**: https://vuejs.org/v2/guide/

Current Tasks:

- [x] Create the index.html page
- [x] Create the site structure
- [x] Create the index.css page
- [x] Create the index.test.js page (this houses CI tests)
- [ ] #3 Build a list of site navigation endpoints 
- [ ] #4 Create the site navigation bar
- [ ] #5 Create the site header
- [ ] #6 Create the site footer
