### ISSUE TITLE
Build Dashboard with site navigation

### ISSUE THREAD

**Issue by ghost** [AldonIsenberg11/Wrestling#2]
We need to start off with getting the website structure setup

Current Tasks:

- [x] Create the index.html page
- [x] Create the index.js page
- [x] Create the index.css page
- [x] Create the index.test.js page (this houses CI tests)
- [ ] #3 Build a list of site navigation endpoints 
- [ ] #4 Create the site navigation bar
- [ ] #5 Create the site header
- [ ] #6 Create the site footer
